# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"

    # Note that the session will be started ONLY if you read or write from it.
    session: true
    serializer: { enable_attributes: true }

    #esi: true
    #fragments: true
    trusted_proxies: "127.0.0.1,172.21.0.0/16,10.0.0.0/8,192.168.0.0/16"
    trusted_headers: [x-forwarded-for, x-forwarded-host, x-forwarded-proto]

    # Forcer HTTPS pour la génération des URLs
    assets:
        base_urls:
            - "https://api.fabler.fr"

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
