services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=hugo.thivel@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    restart: unless-stopped
    networks:
      - fabler_net

  database:
    image: postgres:16-alpine
    container_name: database
    env_file:
      - ./back/.env.prod
    volumes:
      - ./back/db-init:/docker-entrypoint-initdb.d:ro
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "fabler", "-U", "postgres"]
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - fabler_net

  php:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: php
    env_file:
      - ./back/.env.prod
    volumes:
      - ./back:/var/www
      - uploads_data:/var/www/public/uploads
    depends_on:
      - database
    networks:
      - fabler_net

  caddy:
    image: caddy:2
    container_name: caddy
    volumes:
      - ./back:/var/www
      - ./back/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back.rule=Host(`api.fabler.fr`)"
      - "traefik.http.routers.back.entrypoints=websecure"
      - "traefik.http.routers.back.tls.certresolver=myresolver"
      - "traefik.http.services.back.loadbalancer.server.port=80"
    networks:
      - fabler_net

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`app.fabler.fr`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=myresolver"
    networks:
      - fabler_net

  mercure:
    container_name: mercure
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mercure.rule=Host(`mercure.fabler.fr`)"
      - "traefik.http.routers.mercure.entrypoints=websecure"
      - "traefik.http.routers.mercure.tls.certresolver=myresolver"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - fabler_net

volumes:
  traefik_letsencrypt:
  database_data:
  mercure_data:
  mercure_config:
  uploads_data:

networks:
  fabler_net:
