name: Deploy to VPS

on:
  push:
    branches:
      - main
      - ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 52346 -H 51.77.159.52 >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -p 52346 ubuntu@51.77.159.52 "echo ✅ SSH OK"

      - name: Rsync project files to VPS
        run: |
          rsync -avz --exclude-from='.rsyncignore' -e "ssh -p 52346 -i ~/.ssh/id_rsa" --delete ./ ubuntu@51.77.159.52:/home/ubuntu/projet_fabler

      - name: Create .env.prod on VPS
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_ENV: ${{ secrets.APP_ENV }}
          APP_DEBUG: ${{ secrets.APP_DEBUG }}
          APP_UPLOADS_BASE: ${{ secrets.APP_UPLOADS_BASE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          # JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
          JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
          MERCURE_URL: ${{ secrets.MERCURE_URL }}
          MERCURE_PUBLIC_URL: ${{ secrets.MERCURE_PUBLIC_URL }}
          MERCURE_JWT_SECRET: ${{ secrets.MERCURE_JWT_SECRET }}
          MERCURE_PUBLISH_ALLOWED_ORIGINS: ${{ secrets.MERCURE_PUBLISH_ALLOWED_ORIGINS }}
          MERCURE_SUBSCRIBE_ALLOWED_ORIGINS: ${{ secrets.MERCURE_SUBSCRIBE_ALLOWED_ORIGINS }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          CORS_ALLOW_ORIGIN: ${{ secrets.CORS_ALLOW_ORIGIN }}
        run: |
          ssh -i ~/.ssh/id_rsa -p 52346 ubuntu@51.77.159.52 "echo '\
          APP_SECRET=$APP_SECRET
          APP_ENV=$APP_ENV
          APP_DEBUG=$APP_DEBUG
          APP_UPLOADS_BASE=$APP_UPLOADS_BASE
          DATABASE_URL=$DATABASE_URL

          JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
          JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
          JWT_PASSPHRASE=$JWT_PASSPHRASE

          MERCURE_URL=$MERCURE_URL
          MERCURE_PUBLIC_URL=$MERCURE_PUBLIC_URL
          MERCURE_JWT_SECRET=$MERCURE_JWT_SECRET
          MERCURE_PUBLISHER_JWT_KEY=$MERCURE_JWT_SECRET
          MERCURE_SUBSCRIBER_JWT_KEY=$MERCURE_JWT_SECRET
          MERCURE_PUBLISH_ALLOWED_ORIGINS=$MERCURE_PUBLISH_ALLOWED_ORIGINS
          MERCURE_SUBSCRIBE_ALLOWED_ORIGINS=$MERCURE_SUBSCRIBE_ALLOWED_ORIGINS

          POSTGRES_USER=$POSTGRES_USER
          POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          POSTGRES_DB=$POSTGRES_DB

          CORS_ALLOW_ORIGIN=$CORS_ALLOW_ORIGIN' > /home/ubuntu/projet_fabler/back/.env.prod"

      - name: Fix uploads permissions
        run: |
          ssh -i ~/.ssh/id_rsa -p 52346 ubuntu@51.77.159.52 "\
            sudo mkdir -p /home/ubuntu/projet_fabler/back/public/uploads/avatars && \
            sudo chown -R ubuntu:ubuntu /home/ubuntu/projet_fabler/back/public/uploads && \
            sudo chmod -R 775 /home/ubuntu/projet_fabler/back/public/uploads"

      - name: Create JWT keys on VPS
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa -p 52346 ubuntu@51.77.159.52 "\
            mkdir -p /home/ubuntu/projet_fabler/back/config/jwt && \
            printf '%s\n' \"$JWT_SECRET_KEY\" > /home/ubuntu/projet_fabler/back/config/jwt/private.pem && \
            printf '%s\n' \"$JWT_PUBLIC_KEY\" > /home/ubuntu/projet_fabler/back/config/jwt/public.pem && \
            chmod 644 /home/ubuntu/projet_fabler/back/config/jwt/private.pem && \
            chmod 644 /home/ubuntu/projet_fabler/back/config/jwt/public.pem"

      - name: Verify JWT keys
        run: |
          ssh -i ~/.ssh/id_rsa -p 52346 ubuntu@51.77.159.52 "\
            openssl rsa -in /home/ubuntu/projet_fabler/back/config/jwt/private.pem -check -noout && \
            openssl rsa -in /home/ubuntu/projet_fabler/back/config/jwt/private.pem -pubout | diff - /home/ubuntu/projet_fabler/back/config/jwt/public.pem || echo '⚠️ Public key does not match private key'"
